remote_theme: pmarsceill/just-the-docs
#theme: minima
title: Coursebook for Attacks on Implementations 
url: https://orenlab.sise.bgu.ac.il/AttacksonImplementationsCourseBook

description: This is the handbook for the course "Attacks on Secure Implementations", taught in 2020 at Ben-Gurion University by Dr. Yossi Oren.

#collections:
#  book:
#    output: true
#    permalink: /Book/:path
#
#just_the_docs:
#  collections:
#    book:
#      name: Book

#gems:
#  - jekyll-last-modified-at
#  - jekyll-redirect-from
  
webmaster_verifications:
  google: G3nnoOJAuTy9rt3nEkP

plugins:
  - jekyll-seo-tag

